- lib/xandra/connection.ex
- lib/xandra/connection/utils.ex
- lib/xandra/protocol.ex
This change allows us to "negotiate" options in the connection process instead of hardcoding the negotiation logic in the `Xandra.Protocol` module. This will be useful when we have to negotiate compression options at startup.
> Refactor functions around sending startup options

- lib/xandra/batch.ex
- lib/xandra/prepared.ex
- test/integration/batch_test.exs
- test/integration/prepared_test.exs
* Named params for simple queries now raise a friendly error message
* Named params for prepared queries now work by being rewritten to positional params behind the scenes
> Handle named params for prepared queries by rewriting to positional params

- README.md
- lib/xandra.ex
- lib/xandra/authenticator.ex
- lib/xandra/authenticator/password.ex
- lib/xandra/connection.ex
- lib/xandra/connection/utils.ex
- lib/xandra/frame.ex
- lib/xandra/protocol.ex
Support Authentication in Xandra
* Respond to server's auth challenge
* Introduce Xandra.Authenticator behavior
* Support Password Authenticator through `Xandra.Authenticator.Password`
```ex
{:ok, conn} = Xandra.start_link(
host: "127.0.0.1",
port: 9042,
authentication: {Xandra.Authenticator.Password, username: "cassandra", password: "cassandra"}
])
```
> Support Cassandra authentication

- lib/xandra/connection.ex
- lib/xandra/connection/utils.ex
Fixes #116 by passing the the value of compressor (held in state) to `Xandra.Connection.Utils.request_options/2`
> Fix parsing of ping frames when compressed

- lib/xandra.ex
`ConnectionError` is used in  `@type error :: Error.t | ConnectionError.t` (see [`xandra.ex`][1]), but not aliased at the top of the module. 
This results in dialyzer reporting an unknown type (`Unknown type 'Elixir.ConnectionError':t/0`) and also in a missing link in the [documentation for `t:Xandra.error/0`](https://hexdocs.pm/xandra/Xandra.html#t:error/0).
The PR adds an alias for `ConnectionError`.
[1]: https://github.com/lexhide/xandra/blob/70286b118fa17f6b3a436e4f7e3ac0ac451c868a/lib/xandra.ex#L161
> Fix missing alias for ConnectionError

- .travis.yml
- README.md
- docker-compose.yml
- test/docker/Dockerfile.cassandra
- test/docker/wait-for-cassandra.sh
This PR adds support for a Docker environment which sets up all the necessary infrastructure (Cassandra) to run tests. Tests are still run outside of Docker with `mix test`, Docker is only used for setting up Cassandra.
We are using `docker-compose` to spin up Cassandra (foreseeing a future where we could also spin up ScyllaDB in the same way). This means you only need to run `docker-compose up` to spin up the whole testing environment.
The reasons for this PR are two: first of all we can run tests without installing the whole Cassandra package (and eventually ScyllaDB) in an easy and reproducible way. Then, we can do exactly the same on Travis CI.
> Use Docker for testing on Travis

- lib/xandra.ex
- lib/xandra/cluster.ex
- lib/xandra/cluster/control_connection.ex
- lib/xandra/connection.ex
- mix.exs
- mix.lock
- test/integration/authentication_test.exs
- test/integration/clustering_test.exs
- test/xandra_test.exs
Closes #132.
* We dropped support for custom pools. Now `Xandra` uses `DBConnection.ConnectionPool` under the hood.
* We raise on every transaction-related or cursor-related DBConnection callback.
* We changed `Xandra.Cluster` to be its own process with an API that mirrors `Xandra` instead of being a custom pool.
> Rework a bunch of stuff to upgrade to DBConnection ~> 2.0

- .travis.yml
The test is tagged as `:encryption` (see [encryption_test.exs]) but Travis CI tries to run `--only encrypted` (see [.travis.yml]).
[encryption_test.exs]: https://github.com/lexhide/xandra/blob/2e79eeb4dc4f6ed22d808cac99b17d2879a79bfd/test/integration/encryption_test.exs
[.travis.yml]: https://github.com/lexhide/xandra/blob/2e79eeb4dc4f6ed22d808cac99b17d2879a79bfd/.travis.yml
> Fix invocation of encryption test in .travis.yml

- lib/xandra.ex
- lib/xandra/protocol.ex
- test/integration/datatypes_test.exs
They work similarly to `:decimal_format` or `:timestamp_format`. By default, UUID types will be returned in human-readable form (which is a breaking change).
> Add the :uuid_format and :timeuuid_format options

- lib/xandra/cluster/control_connection.ex
- lib/xandra/protocol.ex
- test/integration/datatypes_test.exs
We were:
* decoding `:inet` IPv6 addresses as 16-element tuples with 16 single bytes
* encoding `:inet` IPv6 addresses from 8-element tuples containing 8 strings (the human-readable representation of IPv6 addresses)
I moved both what we encode and what we return when decoding to `:inet.ip6_address/0`, that is, 8-element tuples containing 8 integers. This means that now users can do stuff like fetch an inet from C* and use it directly in `:gen_tcp.connect/4` for example instead of having to do weird conversion.
> Fix :inet type to use 8-element tuples like :inet.ip6_address/0

- README.md
- lib/xandra.ex
- lib/xandra/batch.ex
- lib/xandra/cluster.ex
- lib/xandra/cluster/control_connection.ex
- lib/xandra/connection.ex
- lib/xandra/connection/utils.ex
- lib/xandra/frame.ex
- lib/xandra/prepared.ex
- lib/xandra/protocol.ex
- lib/xandra/simple.ex
Preparation for #144, make the protocol configurable at runtime, add it to the connection state and  store it in the query structs to have it available when encoding and decoding queries.
> Make protocol version configurable at runtime

- lib/xandra/batch.ex
- lib/xandra/page.ex
- lib/xandra/prepared.ex
- lib/xandra/simple.ex
Dialyzer does not support correctly `@opaque`.
When doing something like this
```elixir
{:ok, query} = Xandra.prepare(conn, query)
Xandra.execute(conn, query, params)
```
Dialyzer raise the warning :
> 
> The call
> ```erlang
> 'Elixir.Xandra':execute(
>   _conn@1::atom() | pid() | {atom(),_} | {'via',atom(),_} | #{'__struct__':='Elixir.DBConnection', 'conn_mode':=_, 'conn_ref':=reference(), 'pool_ref':=_},
>   _query@1::'Elixir.Xandra.Prepared':t(),
>   _params@1::any()
> )
> ```
> does not have a term of type
> ```erlang
> binary() | #{'__struct__':='Elixir.Xandra.Batch' | 'Elixir.Xandra.Prepared', _=>_}
> ```
> (with opaque subterms) as 2nd argument
If I understand correctly dialyzer cannot check the field `__struct__` because the type is `opaque`.
By changing the `@opaque` to `@type`, …
> Change opaque to type for dialyzer

- lib/xandra.ex
- lib/xandra/batch.ex
- lib/xandra/connection.ex
- lib/xandra/frame.ex
- lib/xandra/page.ex
- lib/xandra/prepared.ex
- lib/xandra/protocol/v3.ex
- lib/xandra/protocol/v4.ex
- lib/xandra/schema_change.ex
- lib/xandra/set_keyspace.ex
- lib/xandra/simple.ex
- lib/xandra/void.ex
- test/integration/batch_test.exs
- test/integration/prepared_test.exs
- test/integration/results_test.exs
- test/integration/tracing_test.exs
Closes #161.
This PR adds support for tracing (with the `:tracing` option) and adds a `:tracing_id` field to each result struct (page, prepared, schema change, void, set keyspace).
> Tracing support

- CHANGELOG.md
The types in which uuids and timeuuids are returned from `Xandra.execute()` changed: In `v0.10.1` they where returned as binaries, in `0.11.0` they are returned as strings (by default). This should be noted as a breaking change in the Changelog.
In `v0.10.1`:
```
$ iex -S mix
iex(1)> Application.spec(:xandra)[:vsn]
'0.10.1'
iex(2)> {:ok, conn} = Xandra.start_link()
iex(3)> Xandra.execute(conn, "CREATE KEYSPACE test WITH replication = {'class' : 'SimpleStrategy', 
iex(4)> Xandra.execute(conn, "CREATE TABLE test.test (id uuid PRIMARY KEY, field text)")
iex(5)> Xandra.execute(conn, "INSERT INTO test.test (id, field) VALUES (13813fb0-1dd2-11b2-800a-00000000000d, 'foobar')")
iex(6)> Xandra.execute(conn, "SELECT * FROM test.test") |> elem(1) |> Enum.to_list
[
%{
"field" => "foobar",
"id" => …
```
> Declare uuid_format and timeuuid_format as breaking changes

- lib/xandra/cluster.ex
- lib/xandra/cluster/control_connection.ex
Fix for #118. 
I re-used the `Xandra.Cluster.StatusChange` struct in my implementation as it required the smallest amount of change. I think semantically it fits (a successful connection is equivalent to `UP`) but it breaks the mapping of received events to the structs. Please feel free to change this in any way you want!
I also did not touch the code path dealing with the `STATUS_CHANGE=UP` event. I think this can still be useful as it might be faster than re-establishing the control connection (depending on the backoff timing).
> Fix Xandra.Cluster reconnect

- lib/xandra/batch.ex
It accepts Xandra.values(), not just [term] for values
> Fix Xandra.Batch.add spec

- lib/xandra/batch.ex
- lib/xandra/connection.ex
- lib/xandra/prepared.ex
- lib/xandra/prepared/cache.ex
- lib/xandra/simple.ex
- test/integration/use_test.exs
- test/test_helper.exs
Use the keyspace information to add it to `%Prepared{}` structs so that it can be used together with the statement as key in the prepared cache. This avoids erroneously using queries that were prepared against another keyspace.
To do so, response decoding has been moved inside the connection, akin to what was already done in `handle_prepare` to populate the prepared cache. The decode function in query structs is now simply an identity since the result gets there already decoded.
This also includes a minor fixup in the keyspace returned by `setup_all` by `IntegrationCase`.
Fix #179
> Make the connection aware of the current keyspace

- lib/xandra/protocol/v3.ex
- lib/xandra/protocol/v4.ex
- test/integration/batch_test.exs
If there is an statement with a lightweight transaction (e.g `IF NOT EXISTS`), then the returned result will be a page representing the status of that transaction(s).
Because of this, the `new_page/1` function in `v3` and `v4` protocol modules needs to also handle the Batch queries.
Also a small test case for this scenario is added to batch tests.
> Handle `new_page/1` for Batch queries

- lib/xandra/cluster.ex
- lib/xandra/cluster/control_connection.ex
- test/integration/cluster_test.exs
- test/xandra/cluster/control_connection_test.exs
No changes in any public API, just a refactor to make it harder to
screw up when starting a new control connection.
> Use NimbleOptions internally for control conns

- lib/xandra.ex
- lib/xandra/cluster.ex
- lib/xandra/connection.ex
- lib/xandra/options_validators.ex
- test/integration/cluster_test.exs
- test/xandra_test.exs
Closes #215.
This option was internal and only used by Xandra.Cluster. This commit
simplifies the logic so that the cluster uses the public API, too.
> Remove :address/:port in Xandra.start_link/1

- lib/xandra.ex
As a maintainer of a library that uses Xandra and NimbleOptions and passes options through to `Xandra.start_link/` I am interested in documenting the options directly inside my code. For this it would be helpful to be able to access the `start_link_opts_schema`.
> Expose `start_link_opts_schema`

- .github/workflows/main.yml
- docker-compose.scylladb.yml
- lib/xandra.ex
- lib/xandra/batch.ex
- lib/xandra/connection.ex
- lib/xandra/frame.ex
- lib/xandra/options_validators.ex
- lib/xandra/page.ex
- lib/xandra/prepared.ex
- lib/xandra/protocol/protocol.ex
- lib/xandra/protocol/v4.ex
- lib/xandra/protocol/v5.ex
- lib/xandra/schema_change.ex
- lib/xandra/set_keyspace.ex
- lib/xandra/simple.ex
- lib/xandra/void.ex
- test/docker/health-check-services.sh
- test/integration/custom_payload_test.exs
Supersedes https://github.com/lexhide/xandra/pull/185.
Closes #256.
This PR doesn't have any end-to-end testing since neither C* nor ScyllaDB support any built-in custom payload handling.
> Add basic support for custom payloads

- .github/workflows/main.yml
- test/support/mix_tasks/test.native_protocols.ex
Wanted to help finish off this issue https://github.com/lexhide/xandra/issues/244. I made a couple changes:
1. Changed the CI so it uses this alias to run the unit tests.
2. Changed the alias function so that it can pass arguments down to `mix test`. i.e. you can run `mix test.native_protocols --color --only tag_name` and the resulting `mix test` command will run with `--color` and `--only tag_name` switches.
I separated out the clustering test suite into a new job because I didn't work out the best way to create a new alias for it yet. But I can leave this PR open until I get it done and add it here, if you prefer that.
> Add testing mix alias to CI

- lib/xandra.ex
- test/docker/cassandra.dockerfile
- test/integration/generic_test.exs
Closes #266.
There was a bug preventing the use of the `:default_consistency` option,
since we were setting `:consistency` to `:one` as a default, never
actually falling back to `:default_consistency`. With this commit,
`:consistency` defaults to not being present instead.
> Start actually using :default_consistency

- .github/workflows/main.yml
- config/config.exs
- lib/xandra/cluster.ex
- lib/xandra/cluster/control_connection.ex
- mix.exs
- test/integration/cluster_test.exs
- test/integration/clustering_integration_test.exs
- test/support/test_helper.ex
- test/test_helper.exs
- test/xandra/cluster/control_connection_test.exs
- test_clustering/integration_test.exs
Closes https://github.com/lexhide/xandra/issues/226.
This work is not complete per se, but I want to avoid giant PRs.
This has the following changes visible to users:
* `:autodiscovery` is deprecated and now it's always `true` — this seems to be in line with the officially-supproted DataStax drivers (see the [Python one](https://docs.datastax.com/en/developer/python-driver/3.25/api/cassandra/cluster/)).
Things that are still missing:
* a strategy to connect to the "next" node in the control connection
* a working `:priority` load-balancing strategy
cc @jvf, I can't request your review but would love your 👀 on this.
> Use a single control connection per cluster

- lib/xandra.ex
- lib/xandra/cluster.ex
- lib/xandra/cluster/control_connection.ex
- lib/xandra/connection.ex
- test/xandra/cluster/control_connection_test.exs
Closes https://github.com/lexhide/xandra/issues/272.
The idea here is this:
* We have a private `:registry` option that we can give to single connection processes. If given, connections will register themselves in a `:unique` registry under key `{{address, port}, pool_index}` and value `:up | :down`.
* When connections connect, they update their value in the registry to `:up`. When they disconnect, they update it to `:down`.
* `Xandra.Cluster` now starts a registry and passes the `:registry` option to all connections, passing that registry.
* We make the control connection of a cluster one of the `:connection_listeners` (see DBConnection) for connections, so that the control connection receives `{:connected | :disconnected, connection_pid}` events.
* Whenever the control connection …
> Listen for connections/disconnections and detect "down" nodes in `Xandra.Cluster`

- lib/xandra/cluster.ex
- lib/xandra/cluster/control_connection.ex
- lib/xandra/cluster/load_balancing_policy.ex
- lib/xandra/cluster/load_balancing_policy/random.ex
- test/integration/cluster_test.exs
- test/support/test_helper.ex
- test/xandra/cluster/control_connection_test.exs
- test/xandra/cluster/load_balancing_policy/random_test.exs
This PR introduces the idea of a target number of pools that `Xandra.Cluster` should open. Before this, we'd open a pool for every node online, which is not the way to go (especially after #287 will be implemented).
cc @jvf @harunzengin
> Add :target_pools option to Xandra.Cluster

- lib/xandra/cluster.ex
- lib/xandra/cluster/control_connection.ex
- test/xandra/cluster/control_connection_test.exs
Introduces a new message `{:discovered_hosts, [Host.t()]}`.  I wasn't so sure about whether we should introduce a new telemetry event for this, like `:host_discovered`. Not sure how useful it would be to be able to distinguish between a `:host_added` (from cassandra gossip) and `:host_discovered` (from peers table). 
Closes https://github.com/lexhide/xandra/issues/296
> Send discovered_nodes in bulk from control connection

- lib/xandra/cluster/control_connection.ex
- lib/xandra/cluster/status_change.ex
- lib/xandra/cluster/topology_change.ex
- lib/xandra/connection.ex
- lib/xandra/connection/utils.ex
- lib/xandra/frame.ex
- lib/xandra/protocol/protocol.ex
- lib/xandra/protocol/v3.ex
- lib/xandra/protocol/v4.ex
- lib/xandra/protocol/v5.ex
- test/xandra/cluster/control_connection_test.exs
- test/xandra/frame_test.exs
- test/xandra/protocol_test.exs
Closes https://github.com/lexhide/xandra/issues/300.
@harunzengin did you see change events come in in protocol v5 and debug log something? Because by looking at the code it looks like this code should have never worked, for any protocol module.
> Fix MatchError in Xandra.Cluster.ControlConnection

- lib/xandra/connection.ex
- lib/xandra/connection/utils.ex
- lib/xandra/telemetry.ex
The idea here is to reduce the logging spam, and only emit telemetry events. We already had `Xandra.Telemetry`, which provides `attach_default_handler/0`, which attaches a handler that mostly logs the telemetry events.
This PR adds `attach_debug_handler/0`, which is for logs which are really mostly useful when working on Xandra itself, and not for Xandra users.
> Move many logs to Telemetry events

- lib/xandra.ex
- lib/xandra/cluster.ex
- lib/xandra/cluster/pool.ex
- lib/xandra/retry_strategy.ex
- test/integration/retry_strategies_test.exs
- test/support/test_helper.ex
- test/xandra/cluster/pool_test.exs
- test/xandra/cluster_test.exs
This supersedes #329 since I can't make changes to that directly.
cc @harunzengin
> Make retry strategies cluster-aware

- .github/workflows/main.yml
- docker-compose.yml
- lib/xandra/cluster/pool.ex
- lib/xandra/connection.ex
- lib/xandra/telemetry.ex
- test/integration/warning_test.exs
- test/toxiproxy_config.json
- test/xandra/cluster_test.exs
- test/xandra_test.exs
- test/xandra_toxiproxy_test.exs
> Fix tests in CI

- docker-compose.yml
- lib/xandra/connection.ex
- mix.exs
- test/xandra/cluster_test.exs
- test/xandra_toxiproxy_test.exs
> Fix bug with Scylla protocol

- lib/xandra/connection.ex
When calling prepare or execute on a connection, a monitor is started on that connection which is configured to be removed when it receives a reply using the created alias. However it does not always receive a reply using that alias, which can lead to a resource leak where monitors are created and never removed.
This is mostly (only?) a problem when calling prepare on a long running connection from a long running process when the prepared query already is in the cache, because then the connection does not send a reply using the alias. The leaked monitors eventually takes up enough memory to crash the application. In my case, after a few hours.
Example before fix:
```
iex> Process.info(pid(0, 704 ,0), :dictionary) |> elem(1) |> Enum.take(1)
["$initial_call": {Xandra.Connection, :init, 1}] …
```
> Fix monitor leak in Xandra.Connection

- lib/xandra.ex
- lib/xandra/connection.ex
- lib/xandra/connection_error.ex
- test/xandra_test.exs
> Clean up timeouts in the conn and add `:max_concurrent_requests_per_connection`

- lib/xandra.ex
- lib/xandra/connection.ex
> Set connection transport buffer for active socket

- lib/xandra/cluster.ex
- lib/xandra/connection_error.ex
- test/integration/errors_test.exs
Closes https://github.com/whatyouhide/xandra/issues/359
> Catch noproc errors

- lib/xandra/cluster/control_connection.ex
- lib/xandra/connection.ex
- lib/xandra/connection/utils.ex
- lib/xandra/frame.ex
- test/xandra/frame_test.exs
- test/xandra_test.exs
@jvf @harunzengin this PR can be a collaborative attempt at figuring out what the flying horse crab hell is going on with #356.
At the time of opening it, the PR only adds a test to reproduce the timeouts (which does reproduce them ~90% of the time in my experience) and some additional logging.
Most of the time, Xandra *does not receive the frame* that times out. This is weird. I’m running this with a locally-running Dockerized Cassandra in case it helps.
Btw, I’m opening this because I won't have a ton of time to dedicate to this as I’m pretty busy at work, but I figured we can dig in together, especially after @jvf's fantastic reproducing steps and tests in #356 🙃
> Fix decoding multiple frames in a single envelope in native protocol v5

- .github/workflows/main.yml
Docker Compose v1 has been removed from the Ubuntu base image.
You can see the announcement in the actions of the last commit in `main`: Go to one of last jobs, e.g. 
[Test (Elixir 1.17.1, OTP 27.0 — C* 4.1, Scylla 5.2](https://github.com/whatyouhide/xandra/actions/runs/9927802204/job/27423221142), open the "Set up job" details, open "Runner Image" details and follow the [Included Software](https://github.com/actions/runner-images/blob/ubuntu22/20240708.1/images/ubuntu/Ubuntu2204-Readme.md) link which announces [Docker Compose v1 will be removed from images on July, 29](https://github.com/actions/runner-images/issues/9692).
Now actions fail with `docker-compose: command not found`, see for example [here](https://github.com/sonnen/xandra/actions/runs/10831420568). To fix this, we need to …
> Fix docker compose in Github Action

- lib/xandra/cluster/control_connection.ex
- lib/xandra/cluster/pool.ex
- test/xandra/cluster_test.exs
Fixes the reconnectivity issue after all nodes were down.
Sends a `:host_up` event whenever a new control connection is established so that `Xandra.Cluster.Pool` can start a pool and connect to that host.
Also, fixes the issue where the load balancing state diverges from the peers state.
Closes #373.
> Reconnect after all nodes were offline

- lib/xandra.ex
- test/integration/any_consistency_test.exs
`ANY` is the lowest possible CL for writes. Allow queries to run with `:any` consistency instead of crashing.
Closes #380
> Support `ANY` consistency level
