lib/xandra.ex, lib/xandra/protocol.ex
=> Add support for the "serial_consistency" flag

lib/xandra.ex, lib/xandra/protocol.ex
=> Add support for the "timestamp" flag in QUERY/EXECUTE frames

lib/xandra.ex, test/integration/generic_test.exs
I don't know where to test this: suggestions @lexmag?
=> Add Xandra.run/3

lib/xandra/protocol.ex, test/integration/datatypes_test.exs
=> Add support for date, time, smallint, and tinyint types

lib/xandra/protocol.ex, test/integration/datatypes_test.exs
I added this from a branch I already had because someone else was asking for it in the issues.
I will add tests for this, as soon as I have time, probably tomorrow.  I will add fuller tests for using counters in general.
=> Fix counters for encode and decode

lib/xandra.ex, lib/xandra/page.ex, test/integration/paging_test.exs, test/integration/results_test.exs
Also this commit deprecates cursor functionality.
CC @jeremytregunna
=> Make manual paging via the :paging_state option

lib/xandra.ex, lib/xandra/calendar.ex, lib/xandra/prepared.ex, lib/xandra/protocol.ex, lib/xandra/simple.ex, test/integration/datatypes_test.exs
Supersedes #103.
Closes #101 and #94.
=> Support Date, Time, and DateTime natively

lib/xandra.ex, lib/xandra/batch.ex, lib/xandra/connection.ex, lib/xandra/prepared.ex, lib/xandra/protocol.ex, lib/xandra/simple.ex
\cc @jvf if you want to have a look I'd appreciate the second pair of eyes, since you're working with the codebase :)
=> Add :default_consistency in Xandra.start_link/1

lib/xandra.ex, lib/xandra/cluster/control_connection.ex, lib/xandra/connection.ex, test/integration/encryption_test.exs
=> Rename the :ssl option to :encryption

mix.exs, pages/Data types comparison table.md
[ci skip]
Closes #102.
\cc @lexmag
=> Add a page in the docs comparing datatypes

lib/xandra/cluster/control_connection.ex, lib/xandra/cluster/topology_change.ex, lib/xandra/protocol.ex
For now we don't do anything with them, just decode them.
=> Support TOPOLOGY_CHANGE events in the protocol

lib/xandra/connection/utils.ex
=> Remove unused alias

lib/xandra.ex, lib/xandra/cluster.ex, lib/xandra/retry_strategy.ex, test/integration/retry_strategies_test.exs
=> Support cluster-aware retrying when executing queries through cluster

lib/xandra/connection.ex
=> Logger metadata xandra_address should be convertable to string

lib/xandra/cluster.ex, test/integration/cluster_test.exs
=> Use NimbleOptions for validation in Xandra.Cluster

lib/xandra/connection.ex, lib/xandra/simple.ex, lib/xandra/telemetry.ex, mix.exs, test/integration/warning_test.exs
=> Emit Telemetry events for warnings

lib/xandra/frame.ex, test/xandra/frame_test.exs
=> Fix non-self-contained v5 frames

lib/xandra.ex, test/xandra_test.exs
Closes https://github.com/lexhide/xandra/issues/273.
cc @jvf
=> Rescue all DBConnection errors

lib/xandra/cluster/load_balancing_policy/dc_aware_round_robin.ex, lib/xandra/cluster/load_balancing_policy/random.ex, test/integration/cluster_test.exs, test/support/test_helper.ex, test/xandra/cluster/control_connection_test.exs, test/xandra/cluster/load_balancing_policy/dc_aware_round_robin_test.exs
Closes https://github.com/lexhide/xandra/issues/287.
cc @jvf @harunzengin
=> Add DC-aware round-robin load-balancing policy

lib/xandra/cluster.ex, lib/xandra/cluster/control_connection.ex, lib/xandra/telemetry.ex, test/xandra/cluster/control_connection_test.exs
Part of https://github.com/lexhide/xandra/issues/284.
=> Emit "cluster change" Telemetry events

lib/xandra/cluster.ex, lib/xandra/cluster/control_connection.ex, test/xandra/cluster/control_connection_test.exs
Part of https://github.com/lexhide/xandra/issues/284.
cc @jvf @harunzengin
=> Execute control-connection-related Telemetry events

lib/xandra/cluster.ex, lib/xandra/cluster/control_connection.ex, test/integration/cluster_test.exs, test/xandra/cluster/control_connection_test.exs
Closes https://github.com/lexhide/xandra/issues/297.
=> Add health-check timer to control connection

lib/xandra/telemetry.ex, test/xandra/cluster/control_connection_test.exs
See https://github.com/lexhide/xandra/pull/303#issuecomment-1531218159.
=> Fix MatchError in telemetry logger

lib/xandra/cluster.ex, test/integration/cluster_test.exs
Closes https://github.com/lexhide/xandra/issues/307, albeit with a different approach than the one proposed in the issue.
=> Add the :sync_connect option

lib/xandra/cluster/pool.ex
=> Fix leaky messages in Xandra.Cluster.Pool

lib/xandra/cluster/pool.ex
Sends a `:refresh_topology` event when we get a `:host_up` event for a host that we don't know so far.
=> Send :refresh_topology event to control connection when host is unknown
